# Base Settings
title: Your awesome title
author: Some User
email: your-email@domain.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Site URL
url: "http://theme.digitaladapt.com"
baseurl: /

# Avatar, image location override, default /images/avatar.jpg
# avatar: /images/avatar.jpg

# Social Links
rss: rss
twitter_username: digitaladapt
github_username:  digitaladapt
bitbucket_username: digitaladapt
# instagram_username: digitaladapt
# dribbble_username: digitaladapt
# facebook_username: digitaladapt
# flickr_username: digitaladapt
# linkedin_username: digitaladapt
# pinterest_username: digitaladapt
# youtube_username: digitaladapt
# googleplus_username: +digitaladapt

# Mastodon Instances
# mastodon:
# - username: digitaladapt
#   instance: example.com

# Build Settings
destination: /var/www/theme/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

