# Base Settings
title: Your awesome title
#author: Some User
email: your-email@domain.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Site URL
url: "https://theme.digitaladapt.com"
baseurl: /
lang: en

# Matomo Tracking
# matomo_url: "://track.tld"
# matomo_siteId: 1
# google_analytics: "G-XXXXXXXXXX"

# Contact Me About This Page
page_contact: false

# Excerpts
show_excerpts: true
excerpt_separator: <!--more-->

# Avatar, image location override, default /images/avatar.jpg
# avatar: /images/avatar.jpg

# Banner, default location override, default /images/banner.jpg
# this can also be overridden on a per page basis.
# banner: /images/banner.jpg

# Social Links
rss: rss
twitter_username: digitaladapt
#github_username:  digitaladapt
#bitbucket_username: digitaladapt
# "Copy ID" from user menu, may need to enable developer mode to see option
#discord_id_number: "570971366833127425"
#discord_username: "DigitalAdapt#8238"
#keybase_username: digitaladapt
# instagram_username: digitaladapt
# dribbble_username: digitaladapt
# facebook_username: digitaladapt
# flickr_username: digitaladapt
# linkedin_username: digitaladapt
# pinterest_username: digitaladapt
# youtube_username: digitaladapt
# googleplus_username: +digitaladapt

# Mastodon Instances
# mastodon:
# - username: digitaladapt
#   instance: example.com

# Build Settings
destination: public
plugins:
  - jekyll-feed
  - jekyll-seo-tag
